{include file="layout/header.phtml" }
{include file="layout/navigation.phtml"}

<!-- Content Start -->
<div id="main">
    <!-- Title, Breadcrumb Start-->
    <div class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
                    <h2 class="title">Blog Single Post</h2>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
                    <div class="breadcrumbs pull-right">
                        <ul>
                            <li>You are here:</li>
                            <li><a href="index-2.html">Home</a></li>
                            <li><a href="#">Blog</a></li>
                            <li>Blog Single Post</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Title, Breadcrumb End-->
    <!-- Main Content start-->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="posts-block col-lg-9 col-md-9 col-sm-8 col-xs-12 bottom-pad">
                    <div class="row">


                        <div class="col-lg-12">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object dp img-circle" src="http://www.huffmancode.com/img/hardik.jpg" style="width: 100px;height:100px;">
                                </a>
                                <div class="media-body">
                                    <h1 class="media-heading">Course Name:Web database application</h1>
                                    <br/>
                                    <h2>Uni: RMIT</h2><br/>
                                    <h3>Previous Name:</h3><br/>
                                    <h3>Course Code:acs123</h3><br/>
                                    <h3>www.abiduc.com</h3>
                                    <h3>Software Developer at <a href="http://gridle.in">Gridle.in</a></h3>
                                    <hr style="margin:8px auto">

                                    <span class="label label-default">HTML5/CSS3</span>
                                    <span class="label label-default">jQuery</span>
                                    <span class="label label-info">CakePHP</span>
                                    <span class="label label-default">Android</span>
                                </div>
                            </div>

                        </div>



                    </div>
                    </article>

                    <div class="divider"></div>
                    <!-- Reply Section Start -->
                    <div class="reply">

                        <form class="reply" id="reply">
                            <fieldset>

                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <label>Comment: <span>*</span></label>
                                        <textarea class="form-control" rows="3" cols="40" required></textarea>
                                    </div>
                                </div>
                            </fieldset>
                            <button class="btn-normal btn-color" type="submit">Post Reply</button>
                            <div class="clearfix">
                            </div>
                        </form>
                    </div>
                    <br/><br/>
                    <!-- Reply Section End -->
                    <!-- Comments Section Start -->
                    <div class="comment-wrapper">
                        <h3 class="title">Comments</h3>
                        <div class="clearfix"></div>
                        <div class="comments-sec">
                            <ol class="commentlist">
                                <li>
                                    <div class="comment" id="1">
                                        <div class="avatar">
                                            <img alt="" src="img/team/team-member-2.jpg">
                                        </div>
                                        <div class="comment-des">
                                            <div class="arrow-comment">
                                            </div>
                                            <div class="comment-by">
                                                <strong>Simon Jones</strong><span class="date">July 30, 2013</span><span class="reply"><a href="#"><i class="icon-reply"></i> Reply</a></span>
                                            </div>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                            </p>
                                        </div>
                                        <div class="clearfix">
                                        </div>
                                    </div>

                                    <div class="clearfix">
                                    </div><br/><br/><br/>
                                </li>

                                <li>
                                    <div class="comment" id="4">
                                        <div class="avatar">
                                            <img alt="" src="img/testimonial/team-member-3.jpg">
                                        </div>
                                        <div class="comment-des">
                                            <div class="arrow-comment">
                                            </div>
                                            <div class="comment-by">
                                                <strong>Indy Parker</strong><span class="date">July 30, 2013</span><span class="reply"><a href="#"><i class="icon-reply"></i> Reply</a></span>
                                            </div>
                                            <p>
                                                Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
                                            </p>
                                        </div>
                                        <div class="clearfix">
                                        </div>
                                    </div>
                                </li>
                            </ol>
                        </div>
                        <div class="clearfix">
                        </div>
                    </div>
                    <!-- Comments Section End -->
                    <div class="divider"></div>

                </div>
                <div class="sidebar col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <!-- Search Widget Start -->
                    <div class="widget search-form">
                        <div class="input-group">
                            <input type="text" value="Search..." onfocus="if (this.value == 'Search...')
                                          this.value = '';" onblur="if (this.value == '')
                                                      this.value = 'Search...';" class="search-input form-control">
                            <span class="input-group-btn">
                                <button type="submit" class="subscribe-btn btn"><i class="icon-search"></i></button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </div>
                    <!-- Search Widget End -->
                    <!-- Tab Start -->
                    <div class="widget tabs">
                        <div id="horizontal-tabs">
                            <ul class="tabs">
                                <li id="tab1" class="current">Popular</li>
                                <li id="tab2">Recent</li>
                                <li id="tab3">Comments</li>
                            </ul>
                            <div class="contents">
                                <div class="tabscontent" id="content1" style="display: block;">
                                    <ul class="posts">
                                        <li>
                                            <a href="#"><img class="img-thumbnail recent-post-img" alt="" src="img/recent-post-img.jpg"></a>
                                            <p><a href="#">Lorem Ipsum is simply dummy text.</a></p>
                                            <span class="color">27 July 2013</span>
                                        </li>
                                        <li>
                                            <a href="#"><img class="img-thumbnail recent-post-img" alt="" src="img/recent-post-img.jpg"></a>
                                            <p><a href="#">Lorem Ipsum is simply dummy text.</a></p>
                                            <span class="color">30 July 2013</span>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tabscontent" id="content2">
                                    <ul class="posts">
                                        <li>
                                            <a href="#"><img class="img-thumbnail recent-post-img" alt="" src="img/recent-post-img.jpg"></a>
                                            <p><a href="#">Lorem Ipsum is simply dummy text.</a></p>
                                            <span class="color">27 July 2013</span>
                                        </li>
                                        <li>
                                            <a href="#"><img class="img-thumbnail recent-post-img" alt="" src="img/recent-post-img.jpg"></a>
                                            <p><a href="#">Lorem Ipsum is simply dummy text.</a></p>
                                            <span class="color">30 July 2013</span>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tabscontent" id="content3">
                                    <ul class="posts">
                                        <li>
                                            <a href="#"><img class="img-thumbnail recent-post-img" alt="" src="img/recent-post-img.jpg"></a>
                                            <p><a href="#">Lorem Ipsum is simply dummy text.</a></p>
                                            by <span class="color">wptuts+</span>
                                        </li>
                                        <li>
                                            <a href="#"><img class="img-thumbnail recent-post-img" alt="" src="img/recent-post-img.jpg"></a>
                                            <p><a href="#">Lorem Ipsum is simply dummy text.</a></p>
                                            by <span class="color">wptuts+</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Tab End -->
                    <!-- Testimonials Widget Start -->
                    <div class="row">
                        <div class="testimonials widget">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="testimonials-title">
                                    <h3 class="title">Testimonials</h3>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div id="testimonials-carousel" class="testimonials-carousel slide">
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="testimonial item">
                                                <p>
                                                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.
                                                </p>
                                                <div class="testimonials-arrow">
                                                </div>
                                                <div class="author">
                                                    <div class="testimonial-image "><img alt="" src="img/testimonial/team-member-1.jpg"></div>
                                                    <div class="testimonial-author-info">
                                                        <a href="#"><span class="color">Monica Sing</span></a> FIFO Themes
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="testimonial item">
                                                <p>
                                                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.
                                                </p>
                                                <div class="testimonials-arrow">
                                                </div>
                                                <div class="author">
                                                    <div class="testimonial-image "><img alt="" src="img/testimonial/team-member-2.jpg"></div>
                                                    <div class="testimonial-author-info">
                                                        <a href="#"><span class="color">Monzurul Haque</span></a> FIFO Themes
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="testimonial item">
                                                <p>
                                                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.
                                                </p>
                                                <div class="testimonials-arrow">
                                                </div>
                                                <div class="author">
                                                    <div class="testimonial-image "><img alt="" src="img/testimonial/team-member-3.jpg"></div>
                                                    <div class="testimonial-author-info">
                                                        <a href="#"><span class="color">Carol Johansen</span></a> FIFO Themes
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Category Widget Start -->
                    <div class="widget category">
                        <h3 class="title">Categories</h3>
                        <ul class="category-list slide">
                            <li><a href="#">Web Design</a></li>
                            <li><a href="#">Graphic Design</a></li>
                            <li><a href="#">Illustration</a></li>
                            <li><a href="#">Logo Design</a></li>
                            <li><a href="#">Wordpress Themes</a></li>
                        </ul>
                    </div>
                    <!-- Category Widget End -->
                    <!-- Ads Widget Start -->
                    <div class="widget ads">
                        <h3 class="title">Advertisement</h3>
                        <div class="ads-img row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <img class="img-thumbnail" alt="" src="img/ads-small.jpg">
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <img class="img-thumbnail" alt="" src="img/ads-small.jpg">
                            </div>
                        </div>
                        <div class="ads-img row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <img class="img-thumbnail" alt="" src="img/ads-small.jpg">
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <img class="img-thumbnail" alt="" src="img/ads-small.jpg">
                            </div>
                        </div>
                    </div>
                    <!-- Ads Widget End -->
                </div>
                <!-- Sidebar End -->
            </div>
        </div>
    </div>
    <!-- Main Content end-->
</div>
<!-- Content End -->
{include file="layout/footer.phtml"}
