{include file="layout/header.phtml" }
{include file="layout/navigation.phtml"}

<include>

    <div class="container-fluid">

        <div>

<!--            <div class="ha-bg-parallax text-center block-marginb-none" data-type="background" data-speed="20">-->
<!--                <div class="ha-parallax-body">-->
<!--                    <div class="ha-content ha-content-whitecolor">-->
<!--                        <h1>-->
<!--                            Start to search your course</h1>-->
<!--                    </div>-->
<!--                    <div class="ha-parallax-divider-wrapper">-->
<!--                        <span class="ha-diamond-divider-md img-responsive"></span>-->
<!--                        <h1>-->
<!--                       frafdsfsddddf asdf dsfe</h1>-->
<!---->
<!--                    </div>-->
<!---->
<!--                </div>-->
<!--            </div>-->



            <div id="myCarousel" class="carousel slide">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="http://ecx.images-amazon.com/images/I/61KsYJUbJuL._SL1500_.jpg" alt="First slide">
                    </div>
                    <div class="item">
                        <img src="http://www.th7.cn/d/file/p/2015/10/14/ec6dfdb08377dd0f8dd6aac306640079.jpg" alt="Second slide">
                    </div>
                    <div class="item">
                        <img src="http://www.th7.cn/d/file/p/2015/10/14/ec6dfdb08377dd0f8dd6aac306640079.jpg" alt="Third slide">
                    </div>
                </div>
                <!-- 轮播（Carousel）导航 -->
                <a class="carousel-control left" href="#myCarousel"
                   data-slide="prev">&lsaquo;</a>
                <a class="carousel-control right" href="#myCarousel"
                   data-slide="next">&rsaquo;</a>
            </div>


        </div>
        <!-- Content Start -->
        <div id="main">
            <!-- Slider Start-->




            <!-- Slogan Start-->
            <div class="slogan bottom-pad-small">
                <div class="container">
                    <div class="row">
                        <div class="slogan-content">
                            <div class="col-lg-9 col-md-9">
                                <h2 class="slogan-title">The favourite courses today</h2>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="get-started">
                                    <button class="btn btn-special btn-color pull-right">Check all the course</button>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Slogan End-->
            <!-- Main Content start-->
            <div class="main-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="content-box big ch-item bottom-pad-small">
                                <div class="ch-info-wrap">
                                    <div class="ch-info">
                                        <div class="ch-info-front ch-img-1"><i class="icon-fullscreen"></i></div>
                                        <div class="ch-info-back">
                                            <i class="icon-fullscreen"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="content-box-info">
                                    <h3>Responsive Layout</h3>
                                    <p>
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    </p>
                                    <a href="#">Read More <i class="icon-angle-right"></i><i class="icon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="content-box big ch-item bottom-pad-small">
                                <div class="ch-info-wrap">
                                    <div class="ch-info">
                                        <div class="ch-info-front ch-img-1"><i class="icon-eye-open"></i></div>
                                        <div class="ch-info-back">
                                            <i class="icon-eye-open"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="content-box-info">
                                    <h3>Retina Ready</h3>
                                    <p>
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    </p>
                                    <a href="#">Read More <i class="icon-angle-right"></i><i class="icon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="content-box big ch-item">
                                <div class="ch-info-wrap">
                                    <div class="ch-info">
                                        <div class="ch-info-front ch-img-1"><i class="icon-edit"></i></div>
                                        <div class="ch-info-back">
                                            <i class="icon-edit"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="content-box-info">
                                    <h3>Rich Elements</h3>
                                    <p>
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    </p>
                                    <a href="#">Read More <i class="icon-angle-right"></i><i class="icon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Main Content end-->
            <!-- Recent works start-->
            <div class="recentworks bottom-pad">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1">
                            <div class="portfolio-desc">
                                <h3 class="title">What is new today?</h3>
                                <p>Hi,guys,just take a break and check out what happened in uni today as well
                                    as the latest news about melbourne,jobs.</p>
                                <div class="carousel-controls">
                                    <a class="prev" href="#portfolio-carousel" data-slide="prev"><i class="icon-angle-left"></i></a>
                                    <a class="next" href="#portfolio-carousel" data-slide="next"><i class="icon-angle-right"></i></a>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9 col-xs-12">
                            <div class="row">
                                <div id="portfolio-carousel" class="portfolio-carousel slide">
                                    <div class="carousel-inner">
                                        <div class="item active">
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 item animate_afc d2">
                                                <div class="portfolio-item">
                                                    <a href="/code2/assets/img/portfolio/portfolio-1.jpg" class="portfolio-item-link" data-rel="prettyPhoto" >
                                                        <span class="portfolio-item-hover"></span>
                                                        <span class="fullscreen"><i class="icon-search"></i></span><img src="/code2/assets/img/portfolio/portfolio-1.jpg" alt=" "/>
                                                    </a>
                                                    <div class="portfolio-item-title">
                                                        <a href="single-project.html">Insta Genius</a>
                                                        <p>
                                                            Design / Development
                                                        </p>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 item animate_afc d3">
                                                <div class="portfolio-item">
                                                    <a href="/code2/assets/img/portfolio/portfolio-2.jpg" class="portfolio-item-link" data-rel="prettyPhoto" >
                                                        <span class="portfolio-item-hover"></span><span class="fullscreen"><i class="icon-search"></i></span><img src="/code2/assets/img/portfolio/portfolio-2.jpg" alt=" "/>
                                                    </a>
                                                    <div class="portfolio-item-title">
                                                        <a href="single-project.html">YA Sound</a>
                                                        <p>
                                                            Sound / Audio
                                                        </p>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 item animate_afc d4">
                                                <div class="portfolio-item">
                                                    <a href="/code2/assets/img/portfolio/portfolio-3.jpg" class="portfolio-item-link" data-rel="prettyPhoto" >
                                                        <span class="portfolio-item-hover"></span><span class="fullscreen"><i class="icon-search"></i></span><img src="/code2/assets/img/portfolio/portfolio-3.jpg" alt=" "/>
                                                    </a>
                                                    <div class="portfolio-item-title">
                                                        <a href="single-project.html">Nike Shoe</a>
                                                        <p>
                                                            Apareal / Shoe
                                                        </p>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="item">
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 item">
                                                <div class="portfolio-item">
                                                    <a href="/code2/assets/img/portfolio/portfolio-4.jpg" class="portfolio-item-link" data-rel="prettyPhoto" >
                                                        <span class="portfolio-item-hover"></span><span class="fullscreen"><i class="icon-search"></i></span><img src="img/portfolio/portfolio-4.jpg" alt=" "/>
                                                    </a>
                                                    <div class="portfolio-item-title">
                                                        <a href="single-project.html">Camera Icon</a>
                                                        Icon / Device
                                                        </p>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 item">
                                                <div class="portfolio-item">
                                                    <a href="/code2/assets/img/portfolio/portfolio-5.jpg" class="portfolio-item-link" data-rel="prettyPhoto" >
                                                        <span class="portfolio-item-hover"></span><span class="fullscreen"><i class="icon-search"></i></span><img src="img/portfolio/portfolio-5.jpg" alt=" "/>
                                                    </a>
                                                    <div class="portfolio-item-title">
                                                        <a href="single-project.html">Penguin</a>
                                                        <p>
                                                            Animal / Nature
                                                        </p>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 item">
                                                <div class="portfolio-item">
                                                    <a href="/code2/assets/images/portfolio/portfolio-6.html" class="portfolio-item-link" data-rel="prettyPhoto" >
                                                        <span class="portfolio-item-hover"></span><span class="fullscreen"><i class="icon-search"></i></span><img src="img/portfolio/portfolio-6.jpg" alt=" "/>
                                                    </a>
                                                    <div class="portfolio-item-title">
                                                        <a href="single-project.html">Sound Box</a>
                                                        <p>
                                                            Audio / Sound
                                                        </p>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {include file="layout/footer.phtml"}
