{include file="layout/header.phtml" }
{include file="layout/navigation.phtml"}

<!--<div class="container">-->
<!---->
<!--</div>-->
<div class="container ">

            <div class="col-md-6">
                <img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive">
            </div>
            <div class="col-md-6">
                <h1 class="text-primary">Login</h1>
                <div class="row">
                    <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-sm-2">
                                    <label for="inputEmail3" class="control-label">Email</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="email" placeholder="Email"></div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-2">
                                    <label for="inputPassword3" class="control-label">Password</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control" id="password" placeholder="Password">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button id="login_submit" name="login_submit" class="btn btn-default">
                                        Sign in</button>
                                </div>
                            </div>
                    </div>
                </div>
            </div>

</div>
<script type="text/javascript" src="/assets/js/user.js"></script>
{include file="layout/footer.phtml" }
