{include file="layout/header.phtml" }
{include file="layout/navigation.phtml"}

<!--<div class="container">-->
<!---->
<!--</div>-->
<div class="container ">

            <div class="col-md-6">
                <img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" class="img-responsive">
            </div>
            <div class="col-md-6">
                <h1 class="text-primary col-sm-offset-2 col-sm-10">Register</h1><br/>
                <div class="row">
                    <div class="col-md-12">

                            <div class="form-group">
                                <div class="col-sm-2">
                                    <label for="email" class="control-label">Email</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="email" placeholder="Email"></div>
                            </div>
                        <div class="form-group">
                            <div class="col-sm-2">
                                <label for="username" class="control-label">Username</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="username" placeholder="Username"></div>
                        </div>
                            <div class="form-group">
                                <div class="col-sm-2">
                                    <label for="inputPassword3" class="control-label">Password</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control" id="password" placeholder="Password">
                                </div>
                            </div>

                        <div class="form-group">
                            <div class="col-sm-2">
                                <label for="inputPassword3" class="control-label">Re-enter Password</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="password_re" placeholder="Password">
                            </div>
                        </div>


                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <div class="checkbox"><label>
                                            <input type="checkbox"><a href="http://www.baidu.com"> Term and Service</a> </label></div></div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button id="register_submit" name="register_submit" class="btn btn-default">
                                        Submit</button>
                                </div>
                            </div>
                    </div>
                </div>
            </div>

</div>
<script type="text/javascript" src="/assets/js/user.js"></script>
{include file="layout/footer.phtml" }
