{include file="layout/header.phtml" }
{include file="layout/navigation.phtml"}

<div class="container">

    <div class="carousel slide" id="carousel-example" data-interval="false"
         data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png">
                <div class="carousel-caption">
                    <h2>Title</h2>
                    <p>Description</p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#carousel-example" data-slide="prev"><i class="icon-prev  fa fa-angle-left"></i></a>
        <a class="right carousel-control" href="#carousel-example" data-slide="next"><i class="icon-next fa fa-angle-right"></i></a>
    </div>
</div>
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <hr>
                <hr>

            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="media-list">
                    <li class="media">
                        <a class="pull-left" href="#"><img class="media-object" src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" height="64" width="64"></a>
                        <div class="media-body">
                            <h4 class="media-heading">Media heading</h4>
                            <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                                ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
                                tempus viverra turpis.</p>
                        </div>
                    </li>

                </ul>
                <a class="btn  col-md-8">Click me</a>
            </div>
        </div>
    </div>
</div>
{include file="layout/footer.phtml" }
