<!-- Our Clients Start-->
<div class="our-clients">
    <div class="container">
        <div class="row">
            <div class="client">
                <div class="client-logo">
                    <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12">
                        <div class="clients-title">
                            <h3 class="title">Our Clients</h3>
                            <div class="carousel-controls pull-right">
                                <a class="prev" href="#client-carousel" data-slide="prev"><i class="icon-angle-left"></i></a>
                                <a class="next" href="#client-carousel" data-slide="next"><i class="icon-angle-right"></i></a>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div id="client-carousel" class="client-carousel slide">
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item animate_afc d1">
                                            <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/uniimages/rmit.jpg"></a></div>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item animate_afc d2">
                                            <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/uniimages/melbourneuni.jpg"></a></div>
                                        </div>
                                        <!--                                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item animate_afc d3">
                                                                                    <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/clientslogo/logo-3.png"></a></div>
                                                                                </div>
                                                                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item animate_afc d4">
                                                                                    <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/clientslogo/logo-4.png"></a></div>
                                                                                </div>-->
                                    </div>
                                    <!--                                    <div class="item">
                                                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item">
                                                                                <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/clientslogo/logo-5.png"></a></div>
                                                                            </div>
                                                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item">
                                                                                <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/clientslogo/logo-4.png"></a></div>
                                                                            </div>
                                                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item">
                                                                                <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/clientslogo/logo-3.png"></a></div>
                                                                            </div>
                                                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 item">
                                                                                <div class="item-inner"><a href="#"><img alt="Upportdash" src="/code2/assets/img/clientslogo/logo-2.png"></a></div>
                                                                            </div>
                                                                        </div>-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <!-- Testimonials Widget Start -->
                        <div class="row ">
                            <div class="testimonials widget">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="testimonials-title">
                                        <h3 class="title">Testimonials</h3>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div id="testimonials-carousel" class="testimonials-carousel slide animate_afr d5">
                                    <div class="carousel-inner">
                                        <div class="item active">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="testimonial item">
                                                    <p>
                                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.
                                                    </p>
                                                    <div class="testimonials-arrow">
                                                    </div>
                                                    <div class="author">
                                                        <div class="testimonial-image "><img alt="" src="/code2/assets/img/testimonial/team-member-1.jpg"></div>
                                                        <div class="testimonial-author-info">
                                                            <a href="#"><span class="color">Monica Sing</span></a> FIFO Themes
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="item">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="testimonial item">
                                                    <p>
                                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.
                                                    </p>
                                                    <div class="testimonials-arrow">
                                                    </div>
                                                    <div class="author">
                                                        <div class="testimonial-image "><img alt="" src="img/testimonial/team-member-2.jpg"></div>
                                                        <div class="testimonial-author-info">
                                                            <a href="#"><span class="color">Monzurul Haque</span></a> FIFO Themes
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="item">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="testimonial item">
                                                    <p>
                                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                                        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                                                        when an unknown printer took a galley of type.
                                                    </p>
                                                    <div class="testimonials-arrow">
                                                    </div>
                                                    <div class="author">
                                                        <div class="testimonial-image "><img alt="" src="/code2/assets/img/testimonial/team-member-3.jpg"></div>
                                                        <div class="testimonial-author-info">
                                                            <a href="#"><span class="color">Carol Johansen</span></a> FIFO Themes
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Our Clients End -->
</div>
<!-- Content End -->


<!-- Footer Bottom Start -->
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">Copyright &copy; 2014.Company name All rights reserved.<a target="_blank" href="http://www.cssmoban.com/"></a> </div>
            <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                <ul class="social social-icons-footer-bottom">
                    <li class="facebook"><a href="#" data-toggle="tooltip" title="Facebook"><i class="icon-facebook"></i></a></li>
                    <li class="twitter"><a href="#" data-toggle="tooltip" title="Twitter"><i class="icon-twitter"></i></a></li>
                    <li class="dribbble"><a href="#" data-toggle="tooltip" title="Dribble"><i class="icon-dribbble"></i></a></li>
                    <li class="linkedin"><a href="#" data-toggle="tooltip" title="LinkedIn"><i class="icon-linkedin"></i></a></li>
                    <li class="rss"><a href="#" data-toggle="tooltip" title="Rss"><i class="icon-rss"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Footer Bottom End -->
</footer>
<!-- Scroll To Top -->
<a href="#" class="scrollup"><i class="icon-angle-up"></i></a>
</div>
<!-- Wrap End -->

<!-- The Scripts -->
<script src="/code2/assets/js/jquery.min.js"></script>
<script src="/code2/assets/js/bootstrap.js"></script>
<script src="/code2/assets/js/jquery.parallax.js"></script>
<script src="/code2/assets/js/modernizr-2.6.2.min.js"></script>
<script src="/code2/assets/js/revolution-slider/js/jquery.themepunch.revolution.min.js"></script>
<script src="/code2/assets/js/jquery.nivo.slider.pack.js"></script>
<script src="/code2/assets/js/jquery.prettyPhoto.js"></script>
<script src="/code2/assets/js/superfish.js"></script>
<script src="/code2/assets/js/tweetMachine.js"></script>
<script src="/code2/assets/js/tytabs.js"></script>
<script src="/code2/assets/js/jquery.gmap.min.js"></script>
<script src="/code2/assets/js/circularnav.js"></script>
<script src="/code2/assets/js/jquery.sticky.js"></script>
<script src="/code2/assets/js/jflickrfeed.js"></script>
<script src="/code2/assets/js/imagesloaded.pkgd.min.js"></script>
<script src="/code2/assets/js/waypoints.min.js"></script>
<script src="/code2/assets/js/spectrum.js"></script>
<script src="/code2/assets/js/switcher.js"></script>
<script src="/code2/assets/js/custom.js"></script>
<script src="/code2/assets/js/add.js"></script>
</body>
</html>