
<body class="home">

<div class="wrap">
    <!-- Header Start -->
    <header id="header">
        <!-- Header Top Bar Start -->
        <div class="top-bar">
            <div class="slidedown collapse">
                <div class="container">
                    <div class="phone-email pull-left">
<!--                        <a><i class="icon-phone"></i> Call Us : +880 41 723 272</a>-->
                        <a href="mail%40example.html"><i class="icon-envelope"></i> Email : help@courseyell.com</a>
                    </div>
                    <div class="pull-right">
                        <ul class="social pull-left">
                            <li class="facebook"><a href="#"><i class="icon-facebook"></i></a></li>
                            <li class="twitter"><a href="#"><i class="icon-twitter"></i></a></li>
                            <li class="dribbble"><a href="#"><i class="icon-dribbble"></i></a></li>
                            <li class="linkedin"><a href="#"><i class="icon-linkedin"></i></a></li>
                            <li class="rss"><a href="#"><i class="icon-rss"></i></a></li>
                        </ul>
                        <div id="search-form" class="pull-right">
                            <form action="#" method="get">
                                <input type="text" class="search-text-box">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header Top Bar End -->
        <!-- Main Header Start -->
        <div class="main-header">
            <div class="container">
                <!-- TopNav Start -->
                <div class="topnav navbar-header">
                    <a class="navbar-toggle down-button" data-toggle="collapse" data-target=".slidedown">
                        <i class="icon-angle-down icon-current"></i>
                    </a>
                </div>
                <!-- Logo Start -->
                <div class="logo pull-left">
                    <h1>
                        <a href="index-2.html">
                            <img src="/code2/assets/img/logo.png" alt="pixma" width="125" height="60">
                        </a>
                        <button>rmit</button>
                    </h1>
                </div>

                <!-- Logo End -->
                <!-- Mobile Menu Start -->
                <div class="mobile navbar-header">

                    <a class="navbar-toggle" data-toggle="collapse" href=".html" id="mobmenu">
                        <i class="icon-reorder icon-2x"></i>
                    </a>


                </div>
                <!-- Mobile Menu End -->
                <!-- Menu Start -->
                <nav class="collapse navbar-collapse menu">
                    <ul class="nav navbar-nav sf-menu">
                        <li>
                            <div class="container">
                                <div class="row">
                                    <br/>
                                    <div class="span12">
                                        <form id="custom-search-form" class="form-search form-horizontal pull-right">
                                            <div class="input-append span12">
                                                <input type="text" class="search-query mac-style" placeholder="Search">
                                                <button type="submit" class="btn"><i class="icon-search"></i></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            &nbsp;&nbsp;                                &nbsp;&nbsp;

                        </li>
                        <li>
                            <a id="current" href="/">

                                {$home}
                                <div class="container-fluid">

                            </a>

                        </li>
                        <li>
                            <a href="/" class="sf-with-ul">
                                {$school}

                                    <span class="sf-sub-indicator">
                                        <i class="icon-angle-down "></i>
                                    </span>
                            </a>
                            <ul>

                                {section name=sec1 loop=$category}</li>
                                <li>
                                    <a href="#" class="sf-with-ul">
                                        {$category[sec1].name}
                                                <span class="sf-sub-indicator pull-right">
                                                    <i class="icon-angle-right "></i>
                                                </span>
                                    </a>

                                    <ul>
                                        {section name=sec1_shool loop=$category[sec1].schools}</li>

                                        <li><a href="#" class="sf-with-ul">{$category[sec1].schools[sec1_shool].name}</a></li>
                                        {/section}

                                    </ul>
                                </li>
                                {/section}
                            </ul>


                        </li>
                        <li>
                            <a id="" href='/forum'>
                                {$discussion_forum}

                            </a>

                        </li>

                        <li><a  href='/course'>Course</a></li>

                    </ul>
                </nav>
                <!-- Menu End -->
            </div>
        </div>
        <!-- Main Header End -->
    </header>
    <!-- Header End -->