<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script type="text/javascript" src="/assets/js/jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/assets/js/jQuery.md5.js"></script>

	<link href="/assets/css/font-awesome.min.css"   rel="stylesheet" type="text/css">
	<link href="/assets/css/bootstrap.css"rel="stylesheet" type="text/css">
	<title>{$courseyell}</title>

</head>
